// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFd4JJsm07_JXABDhScOBt57yfwB-r_38',
    appId: '1:622148557283:web:ec6f2f274debf6cd95a8d6',
    messagingSenderId: '622148557283',
    projectId: 'flutter-firebase-notific-d894a',
    authDomain: 'flutter-firebase-notific-d894a.firebaseapp.com',
    storageBucket: 'flutter-firebase-notific-d894a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYwyuJRv1vaFc_qVJ7tueJ0zRXNi9QEL4',
    appId: '1:622148557283:android:725622bd811e6a0295a8d6',
    messagingSenderId: '622148557283',
    projectId: 'flutter-firebase-notific-d894a',
    storageBucket: 'flutter-firebase-notific-d894a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq3NkLYHzGllE7WSU2w4gZifXCaMtirKg',
    appId: '1:622148557283:ios:3442394924de5b6d95a8d6',
    messagingSenderId: '622148557283',
    projectId: 'flutter-firebase-notific-d894a',
    storageBucket: 'flutter-firebase-notific-d894a.appspot.com',
    iosBundleId: 'com.example.flutterApplicationFirebaseNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq3NkLYHzGllE7WSU2w4gZifXCaMtirKg',
    appId: '1:622148557283:ios:3442394924de5b6d95a8d6',
    messagingSenderId: '622148557283',
    projectId: 'flutter-firebase-notific-d894a',
    storageBucket: 'flutter-firebase-notific-d894a.appspot.com',
    iosBundleId: 'com.example.flutterApplicationFirebaseNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFd4JJsm07_JXABDhScOBt57yfwB-r_38',
    appId: '1:622148557283:web:de556c45414b00f595a8d6',
    messagingSenderId: '622148557283',
    projectId: 'flutter-firebase-notific-d894a',
    authDomain: 'flutter-firebase-notific-d894a.firebaseapp.com',
    storageBucket: 'flutter-firebase-notific-d894a.appspot.com',
  );
}
